### ISSUE TITLE
Add note in Alert - Currently focused on Southern California Fires

### ISSUE THREAD

**Issue by csmattia** [mor10/firetracker#4]
At the current time we are only focused don SoCal fires, we need to note that to fix the All Fires Category for now.  We can later remove that note I think for now it needs to be there.

**Comment by mor10** [comment]
Added some copy for this. Could use enhancement.

**Comment by producerRae** [comment]
This site provides _community aggregated_ links to resources and is **not** an **official resource**. We're currently following #ThomasFire, #SkirballFire, #RyeFire, and #CreekFire. If you believe there is another fire we should be following, send us an email at communityfiretracker@gmail.com, with the subject **Follow This Fire: _Your Suggestion_**. 

Click through the **links below** to view each resource.

**Comment by mor10** [comment]
Closing this issue. Feel free to reopen.
